import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ppEiko = localFont({
  src: [
    {
      path: "../public/fonts/PPEiko-Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/fonts/PPEiko-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/PPEiko-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-pp-eiko",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`...`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppEiko.variable} bg-paper min-h-full flex flex-col text-coffee`}
      >
        <div className="relative">
          <div className="fixed left-4 xl:left-[50px] 2xl:left-[200px] top-0 bottom-0 w-px bg-coffee/6" />

          <div className="hidden xl:block fixed left-[calc(50px+60px)] 2xl:left-[calc(200px+60px)] top-0 bottom-0 w-px bg-coffee/6" />

          <div className="fixed right-4 xl:right-[50px] 2xl:right-[200px] xl:top-18.5 top-0 bottom-0 w-px bg-coffee/6" />

          <div className="mx-4 xl:mx-[50px] 2xl:mx-[200px]">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
