import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ppEiko = localFont({
  src: [
    {
      path: "../public/fonts/PPEiko-Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/fonts/PPEiko-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/PPEiko-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-pp-eiko",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`...`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppEiko.variable} border-coffee/6 border-l border-r mx-4 bg-paper min-h-full flex flex-col text-coffee`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
